version: "3.1"
services:
  db:
    build:
      context: ./dockerFiles
      dockerfile: database
    container_name: "db" 
    restart: unless-stopped
    ports: 
      - "hostdbport:3306"
    env_file: .env
    environment:
        - MYSQL_DATABASE=exampledb
    volumes:
        - dbdata:/var/lib/mysql
        - ./dbconfig:/etc/mysql/conf.d 
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
        - app-network 
  wordpress:
    build:
      context: ./dockerFiles
      dockerfile: wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - db
      - cache
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=exampledb
      - WP_CLI_ALLOW_ROOT=true
      - WORDPRESS_CONFIG_EXTRA=
          define('WP_REDIS_HOST', 'cache' );
          define('WP_REDIS_PORT', 6379);
          define('WP_REDIS_PASSWORD', 'yourredispassword');
          define('WP_MEMORY_LIMIT', '5120M');
          define('DISABLE_WP_CRON', true);
    volumes:
      - www:/var/www/html
    networks:
      - app-network
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network 
  cache:
    image: redis:7.0.0-alpine
    container_name: cache
    ports:
      - redisport:6379    
    restart: unless-stopped 
    command: redis-server --requirepass yourredispassword
    networks:
      - app-network   
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - webserver
    volumes:
      - certbot-etc:/etc/letsencrypt
      - www:/var/www/html
    command: certonly --webroot --force-renewal --webroot-path=/var/www/html --email yourmail@gmail.com --agree-tos --no-eff-email -d example.com -d www.example.com
                
                
volumes:
  certbot-etc:
  www:
  dbdata:
  
networks:
  app-network:
    driver: bridge
